import { Article } from "./types";

export const elaArticles: Article[] = [
  {
    slug: "central-ideas-and-details",
    section: "Reading & Writing",
    domain: "Information and Ideas",
    title: "Central Ideas and Details",
    skill: "Central ideas and details",
    readMinutes: 5,
    summary: "Find the main point of a short passage and separate it from the supporting detail that props it up.",
    overview: [
      "Central-idea questions ask what the passage as a whole is doing, not what one interesting sentence says. On the digital SAT the passages are short, so the main idea usually appears in the first sentence or the last, with the middle providing evidence.",
      "Detail questions are the opposite: they ask about something stated explicitly. The right answer is always paraphrased from the text, never inferred beyond it. If you cannot point at the words that prove a choice, that choice is wrong.",
      "The most common trap is a choice that is true of one sentence but too narrow to be the main idea, or a choice that is broadly true of the topic but never actually stated. Test every choice against scope: too narrow, too broad, or just right.",
    ],
    tips: [
      "Before looking at the choices, say the passage's point to yourself in one plain sentence.",
      "Give every choice a scope label: too narrow, too broad, distorted, or supported.",
      "For detail questions, locate the proof line and keep your finger on it while eliminating.",
      "Prefer moderate wording; extreme words like always, never, and proves rarely match the text.",
      "Watch transition words such as however and therefore — the main point often follows them.",
    ],
    pitfalls: [
      "Picking a choice that restates only the passage's example.",
      "Using outside knowledge that the passage never supplies.",
      "Choosing a choice because it uses words copied from the text.",
    ],
    problems: [
      {
        prompt: "A passage describes three separate experiments and ends: 'Together, these results suggest that sleep loss impairs short-term memory more than long-term recall.' What is the main idea?",
        choices: ["The first experiment was flawed", "Sleep loss affects short-term memory more than long-term recall", "Sleep research requires many experiments", "Long-term recall is unaffected by anything"],
        correct: 1,
        explanation: "The concluding sentence states the passage's overall claim; the three experiments are supporting evidence, and the other options are either too narrow or unsupported.",
      },
      {
        prompt: "Which of these is a supporting detail rather than a central idea?",
        choices: ["The author argues that urban gardens improve public health", "In one Chicago neighborhood, clinic visits fell by 8 percent", "Urban gardens deserve more funding overall", "The essay's purpose is to defend urban gardens"],
        correct: 1,
        explanation: "A specific statistic about one neighborhood is evidence supporting the broader claim, not the claim itself.",
      },
      {
        prompt: "A choice states something true about the topic but never mentioned in the passage. It is:",
        choices: ["Correct, because it is true", "Correct, if it matches the tone", "Incorrect, because it lacks textual support", "Correct, if it is the most specific choice"],
        correct: 2,
        explanation: "Every correct answer must be provable from the passage; outside truth is irrelevant.",
      },
    ],
  },
  {
    slug: "command-of-evidence-textual",
    section: "Reading & Writing",
    domain: "Information and Ideas",
    title: "Command of Evidence: Textual",
    skill: "Command of evidence (textual)",
    readMinutes: 5,
    summary: "Pick the quotation or finding that would most directly strengthen or weaken a stated claim.",
    overview: [
      "These questions give you a hypothesis, argument, or claim and ask which piece of evidence best supports it. The correct choice must connect to the specific claim, not merely to the general topic.",
      "Read the claim carefully and note exactly what would have to be true for it to hold. Then check each choice against that condition. A choice that discusses the topic but does not address the claim's specific relationship is a distractor.",
      "Some versions ask which evidence would weaken or undermine the claim. Same method, reversed: find the choice that makes the claim's required condition false.",
    ],
    tips: [
      "Restate the claim as an if-then sentence before reading the choices.",
      "Underline the claim's comparison — more than, earlier than, only when — since the evidence must match it.",
      "Eliminate choices that support a related but different claim.",
      "Beware evidence that is about the right topic but the wrong group or time period.",
      "For weaken questions, look for a counterexample, not just missing information.",
    ],
    pitfalls: [
      "Selecting the most dramatic-sounding fact instead of the most relevant one.",
      "Ignoring a qualifier such as 'in colder climates' that limits the claim.",
      "Choosing evidence that restates the claim rather than supporting it.",
    ],
    problems: [
      {
        prompt: "Claim: A plant species grows faster in shaded soil than in full sun. Which finding best supports it?",
        choices: ["The species is found on several continents", "Shaded specimens averaged 12 cm of growth per month versus 7 cm in full sun", "Full-sun specimens produced more flowers", "The soil in both plots had similar acidity"],
        correct: 1,
        explanation: "Only the direct growth comparison between shaded and full-sun specimens addresses the claim's specific comparison.",
      },
      {
        prompt: "Claim: A city's bike-lane expansion reduced car commuting. Which finding would most weaken it?",
        choices: ["Bike ridership rose by 15 percent", "Car commuting stayed flat while a nearby city without new lanes saw the same trend", "The lanes cost more than projected", "Residents said they liked the lanes"],
        correct: 1,
        explanation: "A comparison city showing the same pattern without the intervention removes the link between the lanes and any change in car commuting.",
      },
      {
        prompt: "A claim concerns readers under age 18, but a choice reports data on adults only. That choice is:",
        choices: ["Strong support", "Irrelevant to the claim's group", "A direct contradiction", "Support only if the numbers are large"],
        correct: 1,
        explanation: "Evidence must match the population named in the claim; adult data cannot support a claim restricted to minors.",
      },
    ],
  },
  {
    slug: "command-of-evidence-quantitative",
    section: "Reading & Writing",
    domain: "Information and Ideas",
    title: "Command of Evidence: Quantitative",
    skill: "Command of evidence (quantitative)",
    readMinutes: 5,
    summary: "Read a table or graph accurately and choose the data point that completes an argument.",
    overview: [
      "These questions pair a short text with a table or graph. Your job is to select the choice that both reads the data correctly and serves the argument the text is making.",
      "There are two failure modes to guard against. A choice can misread the figure — wrong row, wrong axis, wrong units — or it can read the figure correctly but not connect to the writer's point. Both are wrong; you need a choice that clears both hurdles.",
      "Start with the figure's title, axis labels, and units. Then reread the sentence the choice must complete and note what relationship the data has to show: an increase, a comparison between two groups, or a specific threshold.",
    ],
    tips: [
      "Check units and scale before comparing numbers, especially percent versus count.",
      "Verify each choice against the figure literally before judging relevance.",
      "The completed sentence must be logical, so read your pick back into the text.",
      "Watch for choices that swap two categories' values.",
      "If two choices are both accurate, keep the one that supports the specific claim.",
    ],
    pitfalls: [
      "Choosing an accurate but irrelevant data point.",
      "Misreading a legend and attributing a value to the wrong group.",
      "Mixing up 'increased by' with 'increased to'.",
    ],
    problems: [
      {
        prompt: "A table shows Group A at 42 percent and Group B at 61 percent. The text claims Group B responded more strongly. Which completion is best?",
        choices: ["Group A's rate of 61 percent exceeded Group B's", "Group B's rate of 61 percent exceeded Group A's 42 percent", "Both groups were near 50 percent", "Group B's rate rose by 61 percentage points"],
        correct: 1,
        explanation: "Only this choice reads the table correctly and states the comparison that supports the claim.",
      },
      {
        prompt: "Why is an accurate data point sometimes still the wrong answer?",
        choices: ["It might be an estimate", "It may not support the specific claim being made", "Graphs are unreliable", "It uses the wrong font"],
        correct: 1,
        explanation: "Correctness of the reading is necessary but not sufficient; the data must also serve the argument in the text.",
      },
      {
        prompt: "A graph's y-axis is labeled 'thousands of tons'. A bar reaches 4. The value is:",
        choices: ["4 tons", "400 tons", "4,000 tons", "40,000 tons"],
        correct: 2,
        explanation: "The axis units multiply the reading: 4 × 1,000 = 4,000 tons.",
      },
    ],
  },
  {
    slug: "inferences",
    section: "Reading & Writing",
    domain: "Information and Ideas",
    title: "Inferences",
    skill: "Inferences",
    readMinutes: 5,
    summary: "Complete a passage with the conclusion that must follow from the information given.",
    overview: [
      "Inference questions end with a blank and ask for the most logical completion. The correct answer is not a creative leap; it is the smallest step the passage forces you to take.",
      "Pay close attention to logical connectors. 'However' signals a contrast, so the blank should reverse the prior idea. 'Therefore' signals a consequence, so the blank should follow from what came before. These words often decide the answer by themselves.",
      "Prefer hedged language. Choices saying 'may', 'suggests', or 'in some cases' are usually safer than choices claiming something is proven or universal, because a short passage rarely establishes that much.",
    ],
    tips: [
      "Predict the blank in your own words before reading choices.",
      "Circle the connector right before the blank and honor its direction.",
      "Reject any choice needing a fact the passage never gives.",
      "Favor moderate claims over absolute ones.",
      "Read the completed sentence aloud mentally to confirm it fits the logic.",
    ],
    pitfalls: [
      "Adding plausible real-world knowledge the passage does not state.",
      "Ignoring a contrast word and choosing a continuation.",
      "Selecting an overly strong conclusion the evidence cannot carry.",
    ],
    problems: [
      {
        prompt: "'The treatment reduced symptoms in laboratory mice. However, ___' Which completion fits?",
        choices: ["it also worked in humans", "it may not produce the same effect in humans", "mice and humans are identical", "the study proves the treatment is safe"],
        correct: 1,
        explanation: "'However' demands a limitation, and a hedged statement about the untested human case is the smallest supported step.",
      },
      {
        prompt: "'All samples from the site contained volcanic glass. Therefore, ___'",
        choices: ["the site likely experienced volcanic activity", "the site is the oldest known", "no other minerals exist there", "the samples were mislabeled"],
        correct: 0,
        explanation: "'Therefore' requires a consequence, and volcanic glass in every sample most directly implies volcanic activity at the site.",
      },
      {
        prompt: "Which wording is generally safest in an inference answer?",
        choices: ["proves conclusively", "always results in", "suggests that", "eliminates any possibility of"],
        correct: 2,
        explanation: "Short passages rarely support absolute claims, so hedged wording like 'suggests that' is usually correct.",
      },
    ],
  },
  {
    slug: "words-in-context",
    section: "Reading & Writing",
    domain: "Craft and Structure",
    title: "Words in Context",
    skill: "Words in context",
    readMinutes: 5,
    summary: "Choose the word or phrase that fits the sentence's precise meaning, tone, and grammar.",
    overview: [
      "Words-in-context questions are the most common item type on the Reading and Writing section. You are given a blank and four vocabulary options, and the correct one must match the meaning the surrounding sentences establish.",
      "The reliable method is prediction. Cover the choices, read the passage, and write your own plain word for the blank. Then find the choice closest to your prediction. This prevents a fancy-sounding word from luring you away from the meaning.",
      "Connotation matters as much as denotation. Two synonyms can differ in whether they are positive, negative, or neutral, and the passage's tone decides which fits. Also check whether the word takes the right preposition and part of speech.",
    ],
    tips: [
      "Predict before reading the choices, every time.",
      "Look for signals of contrast or continuation in the sentence before the blank.",
      "Check connotation: is the author approving, critical, or neutral?",
      "Plug your pick back in and read the full sentence.",
      "Unfamiliar words are not automatically correct — do not choose by difficulty.",
    ],
    pitfalls: [
      "Choosing a common meaning of a word that does not fit this context.",
      "Ignoring tone and picking a negative word in a positive sentence.",
      "Selecting a word that fits meaning but not the grammatical structure.",
    ],
    problems: [
      {
        prompt: "'Her explanation was so ___ that even newcomers followed it easily.' Best choice:",
        choices: ["convoluted", "lucid", "verbose", "tentative"],
        correct: 1,
        explanation: "'Followed it easily' calls for a word meaning clear; lucid fits, while convoluted and verbose suggest the opposite.",
      },
      {
        prompt: "'Critics dismissed the theory as ___, citing its lack of evidence.' Best choice:",
        choices: ["rigorous", "speculative", "definitive", "empirical"],
        correct: 1,
        explanation: "'Lack of evidence' and 'dismissed' set a negative, unproven tone, which matches speculative.",
      },
      {
        prompt: "Why should you predict the word before reading the choices?",
        choices: ["It saves time on the calculator", "It keeps an impressive-sounding but wrong word from tempting you", "It guarantees you know every word", "It makes the passage shorter"],
        correct: 1,
        explanation: "Prediction anchors you to the passage's meaning so difficulty or unfamiliarity does not drive your choice.",
      },
    ],
  },
  {
    slug: "text-structure-and-purpose",
    section: "Reading & Writing",
    domain: "Craft and Structure",
    title: "Text Structure and Purpose",
    skill: "Text structure and purpose",
    readMinutes: 5,
    summary: "Describe what a passage or an underlined sentence is doing rather than what it says.",
    overview: [
      "Purpose questions ask about function. The answer describes the role a sentence or passage plays: introducing a problem, offering a counterexample, qualifying a previous claim, or illustrating a general principle.",
      "The choices are usually written as verb phrases, so evaluate the verb first. If the passage never criticizes anything, a choice starting with 'critique' is out no matter how accurate the rest sounds.",
      "For structure questions about the whole text, track the movement: does it go from claim to evidence, from old view to new view, from problem to solution? Naming that arc in your head makes the right choice obvious.",
    ],
    tips: [
      "Ask 'what job does this sentence do?' rather than 'what does it say?'",
      "Judge the verb in each choice before the rest of the phrase.",
      "For an underlined sentence, read the sentence before and after it.",
      "Note shifts signaled by but, yet, in contrast, or for example.",
      "Summarize the passage's arc in five words before answering.",
    ],
    pitfalls: [
      "Choosing an accurate summary that does not describe a function.",
      "Assigning the author an attitude the text never shows.",
      "Describing only part of a sentence's role.",
    ],
    problems: [
      {
        prompt: "A sentence gives a specific case immediately after a general claim. Its function is to:",
        choices: ["Refute the claim", "Illustrate the claim with an example", "Introduce a new topic", "Summarize the passage"],
        correct: 1,
        explanation: "A specific case following a general claim serves as illustration or supporting evidence.",
      },
      {
        prompt: "A passage presents a long-held belief and then research overturning it. The overall structure is:",
        choices: ["A list of unrelated facts", "A traditional view followed by evidence challenging it", "A step-by-step procedure", "A personal narrative"],
        correct: 1,
        explanation: "The arc moves from an established view to contradicting evidence, a common SAT structure.",
      },
      {
        prompt: "Which choice is a function description rather than a content summary?",
        choices: ["Bees pollinate many crops", "It qualifies the previous claim by noting an exception", "The study lasted six years", "Temperatures rose in spring"],
        correct: 1,
        explanation: "Only this option names what the sentence does in the argument; the others simply restate content.",
      },
    ],
  },
  {
    slug: "cross-text-connections",
    section: "Reading & Writing",
    domain: "Craft and Structure",
    title: "Cross-Text Connections",
    skill: "Cross-text connections",
    readMinutes: 5,
    summary: "Compare two short texts and describe how the second author would respond to the first.",
    overview: [
      "These questions give you Text 1 and Text 2 on the same topic and ask how their authors relate. Before touching the choices, summarize each author's position in a short phrase and note whether they agree, disagree, or partly overlap.",
      "Most correct answers describe a partial relationship: the second author accepts a fact but disputes the interpretation, or agrees with the goal but doubts the method. Full agreement and total dismissal are less common than the choices suggest.",
      "When the question asks how the author of Text 2 would respond to a specific point in Text 1, find that exact point and check what Text 2 actually says about it — not about the topic generally.",
    ],
    tips: [
      "Write a two-word stance for each text before reading choices.",
      "Locate the precise sentence in Text 1 that the question references.",
      "Prefer nuanced choices such as 'would agree in part but note that'.",
      "Eliminate choices asserting a view a text never expresses.",
      "Check that the choice assigns each position to the right author.",
    ],
    pitfalls: [
      "Swapping the two authors' positions.",
      "Overstating disagreement when the texts differ only in emphasis.",
      "Answering from the topic rather than from what each text says.",
    ],
    problems: [
      {
        prompt: "Text 1 says a policy cut costs. Text 2 accepts the savings but argues service quality declined. Text 2's author would most likely:",
        choices: ["Deny that any savings occurred", "Agree savings occurred but question whether the policy was beneficial overall", "Fully endorse Text 1's conclusion", "Argue the policy was never implemented"],
        correct: 1,
        explanation: "Text 2 concedes the factual claim while disputing the overall evaluation, which is the classic partial-disagreement pattern.",
      },
      {
        prompt: "What should you do before reading the answer choices in a cross-text question?",
        choices: ["Summarize each author's stance briefly", "Count the words in each text", "Pick the longer text as authoritative", "Look only at the last sentence of Text 2"],
        correct: 0,
        explanation: "Having each stance in mind prevents distractor choices from reframing the relationship for you.",
      },
      {
        prompt: "A choice describes Text 1's view but attributes it to Text 2. It is:",
        choices: ["Correct if the content is accurate", "Incorrect because the attribution is reversed", "Correct if both authors are scientists", "Correct half the time"],
        correct: 1,
        explanation: "Reversed attribution is a common trap; the content must be assigned to the right author.",
      },
    ],
  },
  {
    slug: "rhetorical-synthesis",
    section: "Reading & Writing",
    domain: "Expression of Ideas",
    title: "Rhetorical Synthesis",
    skill: "Rhetorical synthesis",
    readMinutes: 5,
    summary: "Use bulleted notes to write the sentence that accomplishes a stated rhetorical goal.",
    overview: [
      "You are given a list of research notes and a specific goal, such as 'emphasize a similarity between the two studies' or 'introduce the experiment to an audience unfamiliar with it'. The goal, not elegance, decides the answer.",
      "Read the goal first and turn it into a checklist. If it says emphasize a contrast, the correct sentence must mention both items and mark the difference. If it says explain a term, the sentence must define it.",
      "All four choices are typically accurate uses of the notes. Accuracy is therefore not a discriminator — only goal-fit is. Eliminate every choice that leaves out a required element.",
    ],
    tips: [
      "Read the goal before the bullet points.",
      "Convert the goal into two or three required elements and check each choice against them.",
      "Do not reward a choice for including extra detail the goal did not ask for.",
      "Comparison goals need both sides present in one sentence.",
      "Ignore which bullets look most interesting; follow the goal.",
    ],
    pitfalls: [
      "Choosing the most detailed sentence instead of the goal-matching one.",
      "Picking a sentence that describes only one of two items in a comparison goal.",
      "Assuming a choice is wrong because it feels plain.",
    ],
    problems: [
      {
        prompt: "Goal: emphasize a difference between two methods. Which sentence best fits?",
        choices: ["Method A was developed in 1998", "Method B uses optical scanning, whereas Method A relies on manual sorting", "Both methods are used in laboratories", "Method B is popular"],
        correct: 1,
        explanation: "Only this sentence names both methods and marks the contrast with 'whereas', satisfying the stated goal.",
      },
      {
        prompt: "Goal: introduce a study to readers unfamiliar with it. Best sentence:",
        choices: ["The 2019 study, which tracked bird migration over five years, found earlier spring arrivals", "It found earlier arrivals", "The p-value was below 0.01", "As noted, the trend continued"],
        correct: 0,
        explanation: "An introduction for unfamiliar readers needs identifying context: what the study was, what it did, and what it found.",
      },
      {
        prompt: "If all four choices accurately use the notes, what decides the answer?",
        choices: ["Sentence length", "Which one meets the stated rhetorical goal", "Which uses the most bullets", "Alphabetical order"],
        correct: 1,
        explanation: "Accuracy is shared by all choices, so goal-fit is the only discriminator.",
      },
    ],
  },
  {
    slug: "transitions",
    section: "Reading & Writing",
    domain: "Expression of Ideas",
    title: "Transitions",
    skill: "Transitions",
    readMinutes: 5,
    summary: "Pick the connector that matches the actual logical relationship between two sentences.",
    overview: [
      "Transition questions test logic, not vocabulary. Cover the transition, read the sentence before and the sentence after, and decide the relationship yourself: same direction, opposite direction, cause, example, or sequence.",
      "Group the common transitions by job. Contrast: however, nevertheless, on the other hand, by contrast. Cause and effect: therefore, thus, consequently, as a result. Addition: moreover, furthermore, in addition. Example: for instance, for example. Concession: admittedly, granted.",
      "Two choices from the same group can never both be right, so if you see 'however' and 'nevertheless' among the options, the answer is almost certainly in a different group.",
    ],
    tips: [
      "Determine the relationship before looking at the choices.",
      "Cross out same-meaning pairs — they eliminate each other.",
      "Read the sentence after the blank; the relationship depends on it.",
      "Do not choose a transition because it sounds sophisticated.",
      "Plug your answer in and read both sentences together.",
    ],
    pitfalls: [
      "Selecting a contrast transition between two agreeing sentences.",
      "Using 'therefore' where no cause was established.",
      "Reading only the sentence before the blank.",
    ],
    problems: [
      {
        prompt: "'The material is inexpensive. ___, it degrades quickly in sunlight.' Best transition:",
        choices: ["Therefore", "However", "Similarly", "For example"],
        correct: 1,
        explanation: "The second sentence presents a drawback that opposes the first sentence's advantage, so a contrast transition is needed.",
      },
      {
        prompt: "'Rainfall dropped for three straight years. ___, the reservoir fell to record lows.' Best transition:",
        choices: ["Nevertheless", "In contrast", "Consequently", "Admittedly"],
        correct: 2,
        explanation: "The second sentence is the effect of the first, calling for a cause-and-effect transition.",
      },
      {
        prompt: "If 'moreover' and 'in addition' both appear as choices, what do you know?",
        choices: ["One of them is correct", "Neither is correct, since they mean the same thing", "The passage is about addition", "The answer is the shorter one"],
        correct: 1,
        explanation: "Two interchangeable transitions cannot both be right, so the correct answer belongs to a different logical category.",
      },
    ],
  },
  {
    slug: "boundaries-punctuation",
    section: "Reading & Writing",
    domain: "Standard English Conventions",
    title: "Boundaries: Punctuation Between Clauses",
    skill: "Boundaries (sentence structure and punctuation)",
    readMinutes: 6,
    summary: "Join and separate clauses correctly with periods, semicolons, commas, colons, and dashes.",
    overview: [
      "Start every boundaries question by labeling each side of the punctuation as an independent clause (can stand alone) or a dependent one. That single step answers most of these questions.",
      "Two independent clauses may be joined by a period, a semicolon, or a comma plus a coordinating conjunction (for, and, nor, but, or, yet, so). A comma alone creates a comma splice, and no punctuation at all creates a run-on. A colon requires an independent clause on the left and introduces an explanation or list. Dashes can act like commas or like a colon, but they must be used in a matching pair when they surround an interruption.",
      "Also watch supplementary elements. A nonessential phrase takes commas on both sides; an essential phrase takes none. Never separate a subject from its verb with a single comma.",
    ],
    tips: [
      "Test each side for independence before deciding on punctuation.",
      "A semicolon behaves like a period, so both sides must stand alone.",
      "A colon needs a complete sentence before it, not after it necessarily.",
      "Punctuation surrounding an interruption must match: two commas, two dashes, or two parentheses.",
      "If several choices are grammatically identical, they are all wrong; look for the one that differs meaningfully.",
    ],
    pitfalls: [
      "Comma splices joining two complete sentences with only a comma.",
      "Placing a colon after an incomplete clause such as 'The ingredients are:'",
      "Mixing a comma on one side of an interruption with a dash on the other.",
    ],
    problems: [
      {
        prompt: "Which is correctly punctuated?",
        choices: ["The lab closed early, the samples were left overnight.", "The lab closed early; the samples were left overnight.", "The lab closed early the samples were left overnight.", "The lab closed early: and the samples were left overnight."],
        correct: 1,
        explanation: "Both clauses are independent, so a semicolon is correct. The first is a comma splice and the third is a run-on.",
      },
      {
        prompt: "Which sentence uses the colon correctly?",
        choices: ["The kit includes: a lens, a case, and a strap.", "The kit includes three items: a lens, a case, and a strap.", "The kit: includes three items.", "The kit includes three items; a lens, a case, and a strap."],
        correct: 1,
        explanation: "A colon must follow a complete independent clause, which 'The kit includes three items' satisfies.",
      },
      {
        prompt: "'My brother — who lives in Denver, is visiting.' What is wrong?",
        choices: ["Nothing", "The interruption uses mismatched punctuation marks", "It needs a semicolon", "'Who' should be 'whom'"],
        correct: 1,
        explanation: "An interrupting phrase must be enclosed by matching marks: two dashes or two commas, not one of each.",
      },
    ],
  },
  {
    slug: "form-structure-and-sense",
    section: "Reading & Writing",
    domain: "Standard English Conventions",
    title: "Form, Structure, and Sense",
    skill: "Form, structure, and sense (agreement, verbs, modifiers, pronouns)",
    readMinutes: 6,
    summary: "Fix subject-verb agreement, verb tense, pronoun clarity, and misplaced modifiers.",
    overview: [
      "Subject-verb agreement questions usually bury the subject behind a prepositional phrase or a clause. Cross out everything between the subject and the verb, then check the match. Watch for collective nouns and for phrases like 'along with', which do not change a singular subject to plural.",
      "Verb tense must fit the timeline the passage establishes. Look for date markers and other verbs nearby, and keep tense consistent unless the sentence signals a shift. Pronouns need a single clear antecedent and must agree with it in number.",
      "A modifier must sit next to what it modifies. When a sentence opens with a descriptive phrase followed by a comma, the noun right after the comma must be the thing being described; otherwise the modifier dangles.",
    ],
    tips: [
      "Delete interrupting phrases to expose the true subject.",
      "Match verb tense to the passage's timeline, not to what sounds natural in isolation.",
      "For an opening modifier, check the noun immediately after the comma.",
      "Replace an ambiguous pronoun with the noun to see if meaning is preserved.",
      "Keep items in a list in parallel grammatical form.",
    ],
    pitfalls: [
      "Matching the verb to the nearest noun instead of the subject.",
      "Shifting tense mid-passage without reason.",
      "Leaving a dangling modifier attached to the wrong noun.",
    ],
    problems: [
      {
        prompt: "'The collection of rare manuscripts ___ stored in a climate-controlled vault.' Which verb is correct?",
        choices: ["are", "is", "were", "have been being"],
        correct: 1,
        explanation: "The subject is 'collection', which is singular; 'of rare manuscripts' is a prepositional phrase and does not affect agreement.",
      },
      {
        prompt: "'Walking through the museum, the paintings impressed her.' What is the error?",
        choices: ["Verb tense", "A dangling modifier: the paintings were not walking", "Pronoun agreement", "There is no error"],
        correct: 1,
        explanation: "The opening phrase must describe the noun right after the comma; as written, it describes the paintings.",
      },
      {
        prompt: "Which sentence keeps parallel structure?",
        choices: ["She enjoys hiking, to swim, and cycling", "She enjoys hiking, swimming, and cycling", "She enjoys to hike, swimming, and cycled", "She enjoys hiking, swim, and to cycle"],
        correct: 1,
        explanation: "All three items share the same -ing form, which keeps the list parallel.",
      },
    ],
  },
];
