import { Article } from "./types";

export const algebraArticles: Article[] = [
  {
    slug: "linear-equations-one-variable",
    section: "Math",
    domain: "Algebra",
    title: "Linear Equations in One Variable",
    skill: "Linear equations in one variable",
    readMinutes: 5,
    summary: "Solve, rearrange, and interpret single-variable linear equations, including the no-solution and infinite-solution cases.",
    overview: [
      "A linear equation in one variable can always be written as ax + b = 0, where the variable appears to the first power only. Solving means isolating the variable using inverse operations: undo addition with subtraction, undo multiplication with division, and always do the same thing to both sides.",
      "The digital SAT rarely asks for a plain solve. It hides the equation inside a word problem, buries it under fractions, or asks for the value of an expression such as 3x + 1 rather than x itself. Read the last line of the question before you start solving so you know what you are actually being asked for.",
      "Special cases matter. If the variables cancel and you are left with a true statement such as 5 = 5, every real number is a solution. If you are left with a false statement such as 5 = 7, there is no solution. Questions about the value of a constant that makes an equation have no solution are really asking you to make the x-terms identical while the constants differ.",
    ],
    tips: [
      "Clear fractions first by multiplying every term by the least common denominator — it turns an ugly equation into an easy one.",
      "Distribute carefully before combining like terms, and keep the minus sign attached to whatever follows it.",
      "If the question asks for 2x + 5, solve for x and substitute; do not stop at x and pick the trap answer.",
      "For no solution, set the x-coefficients equal and the constants unequal. For infinitely many, set both equal.",
      "Plug your answer back into the original equation for a five-second check — it catches nearly every sign error.",
      "When the answer choices are simple numbers, backsolving from the middle choice is often faster than algebra.",
    ],
    pitfalls: [
      "Distributing to the first term only, as in 3(x + 4) = 3x + 4.",
      "Forgetting to flip a sign when moving a term across the equals sign.",
      "Answering with x when the question asked for an expression built from x.",
    ],
    problems: [
      {
        prompt: "If 4(x − 3) + 6 = 2x + 8, what is the value of x?",
        choices: ["3", "5", "7", "9"],
        correct: 2,
        explanation: "Distribute: 4x − 12 + 6 = 2x + 8, so 4x − 6 = 2x + 8. Subtract 2x: 2x − 6 = 8. Add 6: 2x = 14, so x = 7.",
      },
      {
        prompt: "For what value of c does the equation 6x + 5 = 2(3x + c) have no solution?",
        choices: ["Any value except 2.5", "2.5", "5", "0"],
        correct: 0,
        explanation: "The right side is 6x + 2c. The x-terms already match, so there is no solution whenever 5 ≠ 2c, that is, whenever c ≠ 2.5. At c = 2.5 the equation is true for every x.",
      },
      {
        prompt: "If (x/3) + (x/4) = 14, what is the value of 2x?",
        choices: ["24", "48", "56", "72"],
        correct: 1,
        explanation: "Multiply both sides by 12: 4x + 3x = 168, so 7x = 168 and x = 24. The question asks for 2x, which is 48.",
      },
    ],
  },
  {
    slug: "linear-equations-two-variables",
    section: "Math",
    domain: "Algebra",
    title: "Linear Equations in Two Variables",
    skill: "Linear equations in two variables",
    readMinutes: 6,
    summary: "Read slope and intercepts out of any form of a two-variable linear equation and connect them to a real-world story.",
    overview: [
      "Two-variable linear equations show up in three forms: slope-intercept y = mx + b, standard Ax + By = C, and point-slope y − y₁ = m(x − x₁). Each form makes something easy: slope-intercept exposes the slope m and the y-intercept b, standard form makes intercepts easy (set the other variable to 0), and point-slope is fastest when you are handed a point and a slope.",
      "Slope is the rate of change: how much y moves per one-unit increase in x. On the SAT this is almost always the per-unit quantity in the story — dollars per hour, liters per minute, degrees per day. The y-intercept is the starting amount, the value when x = 0.",
      "From two points, slope is (y₂ − y₁)/(x₂ − x₁). In standard form Ax + By = C, the slope is −A/B. Knowing that shortcut saves you from rearranging under time pressure.",
    ],
    tips: [
      "Translate the story first: label what x is, what y is, and what the units of the slope must be.",
      "In Ax + By = C, use slope = −A/B and x-intercept = C/A, y-intercept = C/B.",
      "Parallel lines share a slope; perpendicular slopes multiply to −1.",
      "If a question gives a table, compute the slope from any two rows — a linear table has a constant rate.",
      "Check a candidate equation against one given point; the wrong choices usually fail immediately.",
    ],
    pitfalls: [
      "Reversing the slope fraction, computing run over rise.",
      "Reading the constant in standard form as the y-intercept.",
      "Mixing up which variable is the input when the story lists them in the opposite order.",
    ],
    problems: [
      {
        prompt: "A line passes through (2, 7) and (6, 19). What is its equation in slope-intercept form?",
        choices: ["y = 3x + 1", "y = 3x − 1", "y = 4x − 1", "y = 2x + 3"],
        correct: 0,
        explanation: "Slope is (19 − 7)/(6 − 2) = 12/4 = 3. Using (2, 7): 7 = 3(2) + b, so b = 1. The equation is y = 3x + 1.",
      },
      {
        prompt: "A gym charges a one-time fee plus a monthly rate. The total cost for 4 months is $190 and for 9 months is $365. What is the monthly rate?",
        choices: ["$25", "$30", "$35", "$45"],
        correct: 2,
        explanation: "The monthly rate is the slope: (365 − 190)/(9 − 4) = 175/5 = 35 dollars per month.",
      },
      {
        prompt: "What is the slope of the line 6x − 4y = 20?",
        choices: ["−1.5", "1.5", "−6", "5"],
        correct: 1,
        explanation: "Slope in standard form is −A/B = −6/(−4) = 1.5. Solving for y gives y = 1.5x − 5, which confirms it.",
      },
    ],
  },
  {
    slug: "linear-functions",
    section: "Math",
    domain: "Algebra",
    title: "Linear Functions",
    skill: "Linear functions",
    readMinutes: 5,
    summary: "Work with f(x) notation, build linear models from descriptions, and interpret what each piece means in context.",
    overview: [
      "A linear function f(x) = mx + b is the same object as a line, dressed in function notation. f(3) means substitute 3 for x; f(x) = 3 means solve for the input that produces the output 3. Keeping those two directions straight is half the battle.",
      "Interpretation questions are extremely common: 'What does 12 represent in the model C(t) = 12t + 40?' The coefficient of the variable is always a rate per unit of the input, and the standalone constant is always the value at input zero.",
      "Building a model means finding those two numbers from the story. Look for a fixed, one-time amount (the constant) and a repeated per-unit amount (the slope).",
    ],
    tips: [
      "Write the units of the slope out loud: dollars per hour, gallons per mile. It instantly resolves interpretation questions.",
      "f(a) = b tells you the graph contains the point (a, b) — turn function statements into points.",
      "For 'increasing/decreasing', only the sign of the slope matters.",
      "To compare two linear models, set them equal to find where they cross, then test a value on either side.",
      "A table of values is linear only if equal x-steps give equal y-steps.",
    ],
    pitfalls: [
      "Confusing f(x) = 5 with f(5).",
      "Calling the constant term a rate.",
      "Assuming a model holds outside the described domain, such as negative time.",
    ],
    problems: [
      {
        prompt: "The function C(m) = 0.18m + 45 gives the monthly cost, in dollars, of a phone plan with m minutes of international calling. What does 45 represent?",
        choices: ["The cost per minute", "The fixed monthly cost with no international calling", "The maximum monthly cost", "The number of free minutes"],
        correct: 1,
        explanation: "Setting m = 0 gives C(0) = 45, the base cost before any international minutes. The 0.18 is the per-minute rate.",
      },
      {
        prompt: "If f(x) = 7 − 2x, for what value of x does f(x) = −5?",
        choices: ["−6", "1", "6", "12"],
        correct: 2,
        explanation: "Set 7 − 2x = −5, so −2x = −12 and x = 6.",
      },
      {
        prompt: "A linear function g satisfies g(1) = 4 and g(5) = 16. What is g(0)?",
        choices: ["0", "1", "2", "3"],
        correct: 1,
        explanation: "The slope is (16 − 4)/(5 − 1) = 3. From g(1) = 4, g(0) = 4 − 3 = 1.",
      },
    ],
  },
  {
    slug: "systems-of-linear-equations",
    section: "Math",
    domain: "Algebra",
    title: "Systems of Two Linear Equations",
    skill: "Systems of two linear equations in two variables",
    readMinutes: 6,
    summary: "Solve systems by substitution or elimination and recognize when a system has one, none, or infinitely many solutions.",
    overview: [
      "A system of two linear equations asks where two lines meet. Substitution works best when one variable is already isolated or has coefficient 1. Elimination works best when you can add or subtract the equations to cancel a variable, sometimes after multiplying one equation by a constant.",
      "The number of solutions is a slope question. Different slopes means exactly one solution. Same slope with different intercepts means no solution — parallel lines. Same slope and same intercept means infinitely many — the equations describe one line.",
      "Word-problem systems almost always pair a count equation (how many items) with a value equation (total cost, total weight, total points). Set those two up and the algebra is routine.",
    ],
    tips: [
      "Stack the equations and look for a variable whose coefficients are equal or opposite — that is your elimination target.",
      "Multiply an entire equation, every term, when scaling for elimination.",
      "For 'no solution' constant questions, force the coefficient ratios A₁/A₂ = B₁/B₂ ≠ C₁/C₂.",
      "Sometimes the question asks for x + y, which elimination can give you directly without solving for either variable.",
      "Check your pair in both original equations, not just the one you used last.",
    ],
    pitfalls: [
      "Solving for one variable and forgetting to back-substitute for the other.",
      "Sign errors when subtracting equations term by term.",
      "Assuming two equations always have exactly one solution.",
    ],
    problems: [
      {
        prompt: "If 3x + 2y = 19 and x − 2y = −7, what is the value of x?",
        choices: ["1", "3", "5", "7"],
        correct: 1,
        explanation: "Add the two equations: 4x = 12, so x = 3. (Then y = 5.)",
      },
      {
        prompt: "Tickets cost $8 for students and $12 for adults. 30 tickets sold for a total of $300. How many adult tickets were sold?",
        choices: ["10", "15", "18", "20"],
        correct: 1,
        explanation: "With s + a = 30 and 8s + 12a = 300, substitute s = 30 − a: 240 − 8a + 12a = 300, so 4a = 60 and a = 15.",
      },
      {
        prompt: "For which value of k does the system y = 4x + 1 and 8x − 2y = k have infinitely many solutions?",
        choices: ["−2", "−1", "1", "2"],
        correct: 0,
        explanation: "Substituting gives 8x − 2(4x + 1) = k, so −2 = k. Only k = −2 makes the two equations the same line.",
      },
    ],
  },
  {
    slug: "linear-inequalities",
    section: "Math",
    domain: "Algebra",
    title: "Linear Inequalities in One or Two Variables",
    skill: "Linear inequalities in one or two variables",
    readMinutes: 5,
    summary: "Solve inequalities, respect the flip rule, and translate constraint language into systems of inequalities.",
    overview: [
      "Inequalities follow the same algebra as equations with one extra rule: multiplying or dividing both sides by a negative number reverses the direction of the inequality sign. Everything else — distributing, combining, clearing fractions — is identical.",
      "Two-variable inequalities describe regions. y > mx + b is the region above the line, y < mx + b the region below. A solid line means the boundary is included (≤ or ≥); a dashed line means it is not.",
      "Constraint problems give you words that map to symbols: 'at least' is ≥, 'at most' is ≤, 'no more than' is ≤, 'more than' is >, 'fewer than' is <. Build one inequality per constraint, then test candidate points.",
    ],
    tips: [
      "Circle the flip: any time you divide by a negative, write the new sign before continuing.",
      "To test which side of a line a region is on, plug in (0, 0) when the line does not pass through the origin.",
      "For a system, a correct answer must satisfy every inequality — test choices against the tightest constraint first.",
      "Convert 'at least 3 times as many x as y' into x ≥ 3y, not 3x ≥ y; read the direction slowly.",
      "Compound inequalities like 3 < 2x + 1 ≤ 9 are solved by doing the same operation to all three parts.",
    ],
    pitfalls: [
      "Forgetting to flip the sign after dividing by a negative coefficient.",
      "Confusing 'at most' with 'at least'.",
      "Ignoring the implicit constraint that a real-world count cannot be negative.",
    ],
    problems: [
      {
        prompt: "What is the solution to −3x + 7 > 22?",
        choices: ["x > −5", "x < −5", "x > 5", "x < 5"],
        correct: 1,
        explanation: "Subtract 7: −3x > 15. Divide by −3 and flip: x < −5.",
      },
      {
        prompt: "A student needs at least 240 points from tests worth 20 points each and projects worth 50 points each. Which inequality models this?",
        choices: ["20t + 50p ≤ 240", "20t + 50p ≥ 240", "50t + 20p ≥ 240", "20t + 50p = 240"],
        correct: 1,
        explanation: "'At least 240' means the total 20t + 50p must be greater than or equal to 240.",
      },
      {
        prompt: "Which point is a solution to the system y ≥ 2x − 1 and x + y < 6?",
        choices: ["(4, 3)", "(0, −4)", "(1, 2)", "(3, 4)"],
        correct: 2,
        explanation: "At (1, 2): 2 ≥ 2(1) − 1 = 1 is true, and 1 + 2 = 3 < 6 is true. Each other point fails at least one inequality.",
      },
    ],
  },
];
