import { Article } from "./types";

export const dataArticles: Article[] = [
  {
    slug: "ratios-rates-proportions-units",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "Ratios, Rates, Proportional Relationships, and Units",
    skill: "Ratios, rates, proportional relationships, and units",
    readMinutes: 5,
    summary: "Set up proportions correctly and convert units with dimensional analysis so the labels do the work for you.",
    overview: [
      "A ratio compares two quantities; a rate is a ratio with different units; a proportional relationship is one where y = kx, so the ratio y/x is constant. Almost every question here reduces to setting up one honest proportion and cross-multiplying.",
      "Dimensional analysis is the safest method for unit conversion. Write the starting quantity as a fraction, then multiply by conversion factors arranged so the unwanted units cancel diagonally. If your units come out right, your arithmetic setup is right.",
      "Watch for scaling in two dimensions: if a length scale factor is k, areas scale by k² and volumes by k³. Density, speed, and price-per-unit problems are all the same rate machinery wearing different clothes.",
    ],
    tips: [
      "Match units on both sides of a proportion before cross-multiplying — miles with miles, hours with hours.",
      "Write conversion factors as fractions and cancel units explicitly instead of guessing whether to multiply or divide.",
      "For part-to-part ratios like 3:5, the total has 8 parts — build the fraction from the total when the question asks for a share.",
      "Rate × time = amount; rearrange rather than re-deriving each time.",
      "When two quantities are inversely proportional, the product xy stays constant, not the quotient.",
    ],
    pitfalls: [
      "Treating a part-to-part ratio as part-to-whole.",
      "Converting only one of the two units in a compound rate such as km per hour to m per second.",
      "Scaling area by the length factor instead of its square.",
    ],
    problems: [
      {
        prompt: "A machine fills 15 bottles every 4 minutes. At this rate, how many bottles does it fill in 1 hour?",
        choices: ["150", "180", "225", "240"],
        correct: 2,
        explanation: "The rate is 15/4 bottles per minute. In 60 minutes: (15/4) × 60 = 225 bottles.",
      },
      {
        prompt: "The ratio of red to blue marbles in a jar is 3:5, and there are 64 marbles total. How many are red?",
        choices: ["21", "24", "27", "40"],
        correct: 1,
        explanation: "There are 3 + 5 = 8 parts, so each part is 64/8 = 8 marbles. Red gets 3 parts: 3 × 8 = 24.",
      },
      {
        prompt: "A car travels at 90 kilometers per hour. What is this speed in meters per second?",
        choices: ["15", "25", "32.4", "50"],
        correct: 1,
        explanation: "90 km/h × 1000 m per km ÷ 3600 s per hour = 90000/3600 = 25 meters per second.",
      },
    ],
  },
  {
    slug: "percentages",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "Percentages",
    skill: "Percentages",
    readMinutes: 5,
    summary: "Handle percent of, percent change, successive percent changes, and reverse-percent problems without second-guessing.",
    overview: [
      "Percent means per hundred. 'A is p percent of B' becomes A = (p/100) · B. Every basic percent question is that one equation with a different unknown, so identify which of the three slots is missing before you compute.",
      "Percent change is (new − old)/old × 100. The denominator is always the original amount. An increase of 20 percent multiplies by 1.20; a decrease of 20 percent multiplies by 0.80. Successive changes multiply, so up 20 percent then down 20 percent lands at 0.96 of the original, not back where you started.",
      "Reverse-percent questions give you the final amount and ask for the original. Divide rather than subtract: if a price after a 25 percent discount is $60, the original is 60/0.75 = $80.",
    ],
    tips: [
      "Convert percent language into multipliers immediately: 'increased by 8 percent' becomes × 1.08.",
      "For percent-of-percent, multiply the decimals in one chain rather than doing two rounded steps.",
      "Percent greater than means the multiplier exceeds 1; percent of means the multiplier itself.",
      "Use 100 as a stand-in original amount when a question is entirely in percents.",
      "Round only at the very end so intermediate rounding never shifts your answer.",
    ],
    pitfalls: [
      "Dividing by the new value instead of the original in a percent-change calculation.",
      "Adding two successive percent changes together.",
      "Confusing '150 percent of' with '150 percent greater than'.",
    ],
    problems: [
      {
        prompt: "A jacket priced at $80 is discounted 25 percent, and then 10 percent is added at checkout for tax. What is the final price?",
        choices: ["$60.00", "$64.00", "$66.00", "$72.00"],
        correct: 2,
        explanation: "80 × 0.75 = 60, then 60 × 1.10 = 66 dollars.",
      },
      {
        prompt: "After a 20 percent increase, a town's population is 18,000. What was the population before the increase?",
        choices: ["14,400", "15,000", "15,600", "16,200"],
        correct: 1,
        explanation: "Divide by the multiplier: 18000/1.20 = 15,000.",
      },
      {
        prompt: "A value drops from 250 to 200. What is the percent decrease?",
        choices: ["16%", "20%", "25%", "50%"],
        correct: 1,
        explanation: "The change is 50, and the original is 250, so 50/250 = 0.20, a 20 percent decrease.",
      },
    ],
  },
  {
    slug: "one-variable-data",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "One-Variable Data: Distributions, Center, and Spread",
    skill: "One-variable data: distributions and measures of center and spread",
    readMinutes: 6,
    summary: "Compare mean, median, range, and standard deviation, and reason about how outliers and shape affect each.",
    overview: [
      "Mean is the balance point and is dragged toward outliers. Median is the middle value once the data is ordered and barely moves when an extreme value changes. Because of that, a right-skewed distribution has a mean greater than its median, and a left-skewed one has a mean less than its median.",
      "Spread has two common measures on the SAT. Range is simply maximum minus minimum. Standard deviation measures typical distance from the mean: tightly clustered data has a small standard deviation, widely scattered data a large one. You are never asked to compute standard deviation by hand — only to compare.",
      "Data often arrives in a frequency table, dot plot, or histogram. Treat frequency as a count of repeats: the mean is the sum of value × frequency divided by the total frequency, and the median is the value at the middle position of the cumulative counts.",
    ],
    tips: [
      "Order the list before finding the median; with an even count, average the two middle values.",
      "To compare two standard deviations visually, ask which data set hugs its mean more tightly.",
      "Adding the same constant to every value shifts mean and median but leaves range and standard deviation unchanged.",
      "In a frequency table, build a running total to locate the median position quickly.",
      "An outlier's effect is large on the mean and range, small on the median.",
    ],
    pitfalls: [
      "Taking the median of the frequencies instead of the data values.",
      "Assuming a larger range always means a larger standard deviation.",
      "Forgetting to sort the values before picking the middle one.",
    ],
    problems: [
      {
        prompt: "The values 4, 7, 7, 9, 43 are recorded. Which statement is true?",
        choices: ["The mean is less than the median", "The mean equals the median", "The mean is greater than the median", "The range is 9"],
        correct: 2,
        explanation: "The median is 7 and the mean is (4 + 7 + 7 + 9 + 43)/5 = 14. The outlier 43 pulls the mean above the median.",
      },
      {
        prompt: "Data set A is 10, 10, 10, 10 and data set B is 5, 10, 10, 15. Which has the greater standard deviation, and why?",
        choices: ["A, because it has more repeats", "B, because its values are more spread out from the mean", "They are equal, because both means are 10", "A, because its range is larger"],
        correct: 1,
        explanation: "Both have a mean of 10, but A has zero spread while B's values sit 5 units away from the mean, so B has the greater standard deviation.",
      },
      {
        prompt: "A frequency table lists the value 2 four times, 5 three times, and 9 three times. What is the median?",
        choices: ["2", "5", "6", "9"],
        correct: 1,
        explanation: "There are 10 values in order: 2,2,2,2,5,5,5,9,9,9. The 5th and 6th values are both 5, so the median is 5.",
      },
    ],
  },
  {
    slug: "two-variable-data-scatterplots",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "Two-Variable Data: Models and Scatterplots",
    skill: "Two-variable data: models and scatterplots",
    readMinutes: 6,
    summary: "Read a line or curve of best fit, predict values, and interpret residuals and model parameters in context.",
    overview: [
      "A scatterplot shows paired data, and a line of best fit summarizes the trend. The slope of that line is the predicted change in y per one-unit increase in x, and the y-intercept is the predicted value when x is zero — meaningful only if x = 0 is inside the plausible range.",
      "Prediction questions ask you to read the model at a given x. Use the fitted line, not an individual data point, unless the question says otherwise. The difference between an actual data point and the model's prediction is the residual: positive when the point sits above the line, negative when below.",
      "Not every trend is linear. Data that curves upward at an increasing rate suggests an exponential model; data that rises then falls suggests a quadratic. Choose the model whose shape matches the cloud of points.",
    ],
    tips: [
      "Read predictions off the line, not the nearest dot.",
      "Interpret the slope with units in the sentence: 'about 2.5 more dollars per additional mile.'",
      "A residual question is a subtraction: actual minus predicted.",
      "Beware extrapolating far beyond the data — the SAT sometimes tests that this is unreliable.",
      "For 'which model fits best', check the shape first, then test one or two points.",
    ],
    pitfalls: [
      "Reversing actual and predicted when computing a residual.",
      "Interpreting the intercept in a context where x = 0 is impossible.",
      "Calling a strong association a cause.",
    ],
    problems: [
      {
        prompt: "A line of best fit is y = 3.2x + 12, where x is hours studied and y is score. What does 3.2 represent?",
        choices: ["The score of someone who studies zero hours", "The predicted score increase per additional hour studied", "The total number of hours studied", "The maximum possible score"],
        correct: 1,
        explanation: "The slope of a best-fit line is the predicted change in the output per one-unit increase in the input: 3.2 points per extra hour.",
      },
      {
        prompt: "For the model y = 3.2x + 12, a student who studied 5 hours actually scored 30. What is the residual?",
        choices: ["−2", "2", "28", "30"],
        correct: 1,
        explanation: "Predicted is 3.2(5) + 12 = 28. Residual is actual minus predicted: 30 − 28 = 2.",
      },
      {
        prompt: "A scatterplot's points rise slowly at first and then much more steeply, never turning back down. Which model fits best?",
        choices: ["Linear", "Exponential growth", "Linear with negative slope", "A horizontal line"],
        correct: 1,
        explanation: "A steadily steepening rise with no turning point is characteristic of exponential growth rather than a constant-rate linear model.",
      },
    ],
  },
  {
    slug: "probability-and-conditional-probability",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "Probability and Conditional Probability",
    skill: "Probability and conditional probability",
    readMinutes: 5,
    summary: "Compute probabilities from two-way tables and pin down exactly which group is the denominator.",
    overview: [
      "Probability is favorable outcomes divided by total outcomes. On the digital SAT the outcomes almost always live in a two-way table, so the real skill is deciding which cell is the numerator and which total is the denominator.",
      "Conditional probability restricts the universe. 'Given that the person is a senior' means your denominator is the senior row total, not the grand total. Phrases like 'among', 'of those who', and 'given that' are all signals to shrink the denominator.",
      "For independent events, multiply: P(A and B) = P(A) · P(B). For either-or events that cannot overlap, add. The complement rule P(not A) = 1 − P(A) turns many 'at least one' questions into a single subtraction.",
    ],
    tips: [
      "Underline the conditioning phrase and circle the corresponding row or column total before computing.",
      "Write the fraction before simplifying so you can double-check both parts.",
      "Convert to a decimal only if the choices are decimals.",
      "'At least one' usually means 1 minus the probability of none.",
      "Check that your probability is between 0 and 1; a value above 1 means you swapped numerator and denominator.",
    ],
    pitfalls: [
      "Using the grand total as the denominator for a conditional probability.",
      "Adding probabilities of events that can happen together.",
      "Reading the wrong table cell because rows and columns were swapped.",
    ],
    problems: [
      {
        prompt: "In a survey, 40 of 100 students are seniors, and 24 of those seniors have a job. What is the probability that a randomly selected senior has a job?",
        choices: ["0.24", "0.40", "0.60", "0.64"],
        correct: 2,
        explanation: "Condition on seniors, so the denominator is 40: 24/40 = 0.60.",
      },
      {
        prompt: "A fair coin is flipped twice. What is the probability of getting at least one head?",
        choices: ["0.25", "0.50", "0.75", "1.00"],
        correct: 2,
        explanation: "P(no heads) = 0.5 × 0.5 = 0.25, so P(at least one head) = 1 − 0.25 = 0.75.",
      },
      {
        prompt: "A bag has 5 red and 15 blue chips. One chip is drawn at random. What is the probability it is red?",
        choices: ["1/5", "1/4", "1/3", "3/4"],
        correct: 1,
        explanation: "There are 20 chips total, so P(red) = 5/20 = 1/4.",
      },
    ],
  },
  {
    slug: "inference-and-margin-of-error",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "Inference from Sample Statistics and Margin of Error",
    skill: "Inference from sample statistics and margin of error",
    readMinutes: 5,
    summary: "Turn a sample estimate plus a margin of error into a plausible-range statement about the whole population.",
    overview: [
      "A sample statistic estimates a population parameter. The margin of error describes how far off that estimate is likely to be, so an estimate of 62 percent with a 3 percent margin of error gives a plausible interval from 59 percent to 65 percent for the true population value.",
      "Two things shrink the margin of error: a larger sample size and a lower required confidence level. Increasing the sample size is the option the SAT tests most often. The margin of error says nothing about whether the sample was chosen well.",
      "Generalizing results requires random selection from the population you want to describe. If the sample came from only one club, one city, or volunteers, the conclusion applies only to that narrower group.",
    ],
    tips: [
      "Build the interval by adding and subtracting the margin from the estimate, then compare it with the answer choices.",
      "Choose the answer that says 'plausible' or 'likely between', not the one that claims certainty.",
      "Bigger sample means smaller margin of error — that pairing is almost always the right choice.",
      "Check which population the sample was drawn from before accepting a generalization.",
      "The margin of error applies to the population parameter, not to individual people.",
    ],
    pitfalls: [
      "Claiming the true value definitely equals the sample estimate.",
      "Generalizing a convenience sample to everyone.",
      "Thinking a larger margin of error means a better study.",
    ],
    problems: [
      {
        prompt: "A random sample of voters gives 54 percent support with a margin of error of 4 percent. Which conclusion is best supported?",
        choices: ["Exactly 54 percent of all voters support it", "The true support is plausibly between 50 and 58 percent", "At least 58 percent support it", "The sample was too small to say anything"],
        correct: 1,
        explanation: "The estimate plus and minus the margin of error gives a plausible interval of 50 to 58 percent for the population value.",
      },
      {
        prompt: "A researcher wants to reduce the margin of error in a follow-up study. What should she do?",
        choices: ["Survey more people, selected at random", "Survey the same number of people twice", "Increase the confidence level", "Only survey people who responded quickly"],
        correct: 0,
        explanation: "A larger random sample reduces the margin of error. Raising the confidence level widens it, and non-random selection introduces bias.",
      },
      {
        prompt: "Students were surveyed only at a school's robotics club. The results can be generalized to which group?",
        choices: ["All students in the country", "All students at that school", "Members of that robotics club", "All robotics students everywhere"],
        correct: 2,
        explanation: "Because the sample was drawn only from the robotics club, the conclusion applies only to that club's membership.",
      },
    ],
  },
  {
    slug: "evaluating-statistical-claims",
    section: "Math",
    domain: "Problem-Solving and Data Analysis",
    title: "Evaluating Statistical Claims: Observational Studies and Experiments",
    skill: "Evaluating statistical claims (observational studies and experiments)",
    readMinutes: 5,
    summary: "Decide when a study supports a causal claim and when it can only report an association.",
    overview: [
      "Two design features decide what a study can claim. Random selection of subjects from a population allows you to generalize to that population. Random assignment of subjects to treatment groups allows you to claim cause and effect.",
      "An observational study watches what already happens and can only report association, because lurking variables may explain the pattern. An experiment intervenes and randomly assigns treatments, which balances out lurking variables and licenses a causal conclusion — but only for the population the subjects came from.",
      "So the strongest possible conclusion appears when both features are present: randomly selected and randomly assigned. With neither, you can only describe the specific group studied.",
    ],
    tips: [
      "Scan the question stem for the words 'randomly selected' and 'randomly assigned' — they decide the answer.",
      "If assignment was not random, eliminate every choice containing cause, effect, or 'because'.",
      "If selection was not random, eliminate every choice generalizing beyond the group studied.",
      "Prefer cautious wording: 'associated with', 'tends to', 'is likely'.",
      "A big sample does not fix a bad design; randomization is what matters.",
    ],
    pitfalls: [
      "Reading correlation in an observational study as causation.",
      "Generalizing an experiment on volunteers to the general public.",
      "Assuming a well-known result makes a poorly designed study valid.",
    ],
    problems: [
      {
        prompt: "Researchers randomly selected 500 adults from a city and randomly assigned them to a new exercise program or a control group. What is the strongest valid conclusion?",
        choices: ["The program causes the observed change for adults in that city", "The program is associated with the change for these 500 adults only", "The program causes the change for all adults worldwide", "No conclusion is possible"],
        correct: 0,
        explanation: "Random assignment supports causation, and random selection from the city supports generalizing to that city's adults, but not beyond it.",
      },
      {
        prompt: "A survey finds that students who eat breakfast have higher grades. Which conclusion is appropriate?",
        choices: ["Eating breakfast raises grades", "Higher grades cause students to eat breakfast", "Eating breakfast is associated with higher grades", "Breakfast has no effect on grades"],
        correct: 2,
        explanation: "This is observational with no random assignment, so only an association can be reported; a lurking variable such as household routine could explain both.",
      },
      {
        prompt: "Which feature of a study allows a cause-and-effect conclusion?",
        choices: ["A large sample size", "Random assignment of subjects to groups", "Random selection of subjects", "Collecting data over a long period"],
        correct: 1,
        explanation: "Random assignment balances lurking variables across groups, which is what licenses a causal claim. Random selection governs generalizability instead.",
      },
    ],
  },
];
