import { AppLayout } from "@/components/AppLayout";
import { GlassCard } from "@/components/GlassCard";
import {
  Target,
  CalendarDays,
  Sparkles,
  TrendingDown,
  BarChart3,
  ShoppingBag,
  UserCircle,
  Lightbulb,
  Compass,
  PawPrint,
} from "lucide-react";

const sections = [
  {
    icon: Compass,
    title: "Get oriented",
    body: "Your Dashboard is mission control. Check your streak, projected SAT range, and today's recommended routine before diving into anything else. The app generates a fresh routine each day based on the topics you're weakest in.",
  },
  {
    icon: Target,
    title: "Practice the right way",
    body: "Use the Practice tab for adaptive modules and short drills. Module 1 calibrates your difficulty for Module 2 — don't rush. Treat short drills (10–15 min) as warm-ups, and full simulations as benchmarks (every 7–10 days).",
  },
  {
    icon: CalendarDays,
    title: "Daily Plan",
    body: "Each task is generated by the Coach to attack your weakest skills. Complete them in order. Done tasks get a strikethrough so you can see your progress at a glance.",
  },
  {
    icon: TrendingDown,
    title: "Weak Areas",
    body: "This page shows topics you've missed most, ordered by severity. Don't grind through old questions — instead, jump into a fresh drill on that topic. Repeating memorized questions doesn't build skill.",
  },
  {
    icon: Sparkles,
    title: "Coach articles",
    body: "Read at least one strategy article per week. They contain the high-leverage tactics (75-second discipline, point economy, elimination logic) that actually move scores.",
  },
  {
    icon: BarChart3,
    title: "Trust the score range",
    body: "Your projected score is shown as a range (e.g. 1240–1300), not a single number. The range narrows as you complete more drills. Hard questions count more than easy ones.",
  },
  {
    icon: PawPrint,
    title: "Your study companion",
    body: "Buddy the Study Pup earns you a 20% SP bonus when energetic. Feed treats earned from drills to keep energy up. If they fall asleep, run the Wake-Up Quiz to revive them.",
  },
  {
    icon: ShoppingBag,
    title: "The Store",
    body: "Spend StudyPoints (SP) on cosmetics for Buddy — hats, accessories, and outfits. Claim your free daily SP every day to stack up faster.",
  },
  {
    icon: UserCircle,
    title: "Profile & badges",
    body: "Your rank evolves every 500 XP within your tier. Earn badges through milestones (focus minutes, accuracy streaks, level ups). Set a target score and test date so the engine can calibrate.",
  },
];

const tips = [
  "Aim for 30–45 minutes of focused practice per day — consistency beats marathons.",
  "Always review explanations on drills you got wrong; mastery > volume.",
  "Save full-length simulations for once a week. They are exhausting; protect them.",
  "Use 'Submit Module' only after flagging questions you want to revisit. Flagged items show on the review screen.",
  "Claim your free daily SP every day and feed Buddy treats to keep the 20% SP bonus active.",
];

const Help = () => (
  <AppLayout>
    <div className="flex flex-col gap-2 mb-8">
      <span className="text-xs uppercase tracking-[0.25em] text-secondary">Mission Briefing</span>
      <h1 className="font-display text-4xl sm:text-5xl font-bold">
        How to use <span className="text-gradient-nebula">NovaSAT</span>
      </h1>
      <p className="text-muted-foreground max-w-2xl">
        A quick guide so you can extract maximum score growth from every minute you spend in the app.
      </p>
    </div>

    <div className="grid gap-4 md:grid-cols-2 mb-10">
      {sections.map((s) => (
        <GlassCard key={s.title} className="!p-5">
          <div className="flex items-start gap-3">
            <div className="h-10 w-10 rounded-lg bg-primary/15 border border-primary/30 flex items-center justify-center shrink-0">
              <s.icon className="h-5 w-5 text-primary" />
            </div>
            <div className="min-w-0">
              <h3 className="font-display text-lg font-semibold">{s.title}</h3>
              <p className="text-sm text-muted-foreground mt-1.5 leading-relaxed">{s.body}</p>
            </div>
          </div>
        </GlassCard>
      ))}
    </div>

    <GlassCard variant="purple" className="!p-6">
      <div className="flex items-center gap-2 mb-3">
        <Lightbulb className="h-5 w-5 text-warning" />
        <h2 className="font-display text-2xl font-semibold">Power-user tips</h2>
      </div>
      <ul className="space-y-2.5">
        {tips.map((t, i) => (
          <li key={i} className="text-sm text-muted-foreground flex gap-2">
            <span className="text-secondary mt-0.5">▸</span>
            <span>{t}</span>
          </li>
        ))}
      </ul>
    </GlassCard>
  </AppLayout>
);

export default Help;
